### ISSUE TITLE
Create some Mockups

### ISSUE THREAD

**Issue by djalmaaraujo** [linusg/spotifube#1] opened 2017-10-17 12:47 UTC
Should this be a tray application or a full window? Might be better to not be a tray, since this is something that you don't use everyday.

- [x] Create a mockup and upload here

**Comment by linusg** [comment] 2017-11-20 14:22
I won't go for a tray application but rather for a single-window application you manually invoke and close when done.

Even though I do not draw mockups that often, I would be happy starting on one and then move on to the actual coding stuff after having some of [these decided](https://github.com/djalmaaraujo/spotifube/issues/3).

**Comment by djalmaaraujo** [comment] 2017-11-20 14:57
@linusg I agree. Tray is more like a daily-use app, this one is for a few usage.

**Comment by linusg** [comment] 2017-11-20 15:06
...or for applications where a real windowed-UI would be overkill, e.g. Redshift or Diodon (clipboard manager) :wink:
I better leave making the mockup to you as I currently have no great tool for this. Bringing life into the UI then is what I really love doing :smile: 

Also I will leave the decision completely to you, but as I'm planning to actively contribute to this project as I do on the spotify-downloader repo (where I also thought about starting a UI wrapper as this one some time ago), you may add me as a collaborator.

**Comment by djalmaaraujo** [comment] 2017-11-20 15:49
@linusg Sure. I will try to provide some mockups. Let's try to have some "user oriented stories"? How you want to use this UI?

- We want to drag and drop a playlist/song/album link?
- We want to drang and drop a *.txt file generated?
- A very simple UI would be enough?
- What would be the most important feature for the MVP?

Example of user stories:

" As a user I want to be able to open the app and already drag a playlist link and get the list of songs loaded with a button to download the *.txt "

" As a user I want to be able to drag a *.txt file with a list of spotify songs and download the mp3s to a default folder "

**Comment by linusg** [comment] 2017-11-20 15:58
> We want to drag and drop a playlist/song/album link?

Drag and drop is a great thing, but I think dragging links is rather unintuitive. I would go for an `<input>` here.

> We want to drang and drop a *.txt file generated?

Let's do this. Even though I guess most users would use use a feature like "enter playlist url here and click download". Still useful though.

> A very simple UI would be enough?

Let's start with a simple one, adding more features as time goes on. I would set the goal to a fully-functional wrapper of all spotify-downloader features, meaning there should be continued work on this particular project as development on our side goes on.

Another idea I have in mind and don't want to forget, therefore writing it down: what about asking for a target path the first time one presses the "download and convert" (or whatever) button, stating the input will be saved and can be changed later? Most will probably store all their music at one place.

**Comment by djalmaaraujo** [comment] 2017-11-20 16:02
I like your suggestions, but while I like the idea of having all features, this is not good for MVP or to have a good pace for a version 0.1, you know?

I think the idea of pasting a playlist link/song/album and hit download to a specific folder is a good start.

Also, we need to find a way to embed the CLI into this app or as a first version, we just put a link with instructions to the user have the CLI installed already.

**Comment by linusg** [comment] 2017-11-20 16:06
Sure, it's meant to be the long-time goal, the final aim :wink:
Surely we have to start small with v0.1. Indeed, making a working download button for a given playlist url seems to be a good start.

For the beginning invoking python and passing the necessary parameters to the script would be sufficient. Later I would even add a check, if python, the script (which we could possibly embed, yes) and ffmpeg are accessible.

**Comment by djalmaaraujo** [comment] 2017-11-20 16:09
👍 

I will deliver some mockups by the end of the week, maybe. Let's see how it goes

**Comment by sdhutchins** [comment] 2017-11-21 04:44
Hello! I'm still interested in contributing. I have a solid background in html/css and some javascript. I agree with starting with a very simple UI as well & copy/paste of a link.

**Comment by djalmaaraujo** [comment] 2017-11-23 15:40
@sdhutchins Feel free to contribute. We will have some mockups in the next days

**Comment by djalmaaraujo** [comment] 2017-11-24 14:34
We won't have mockups for today. I will try for next week, trying to find the right schedule for this.

**Comment by linusg** [comment] 2017-11-24 15:22
Probably @sdhutchins is working on something?

**Comment by sdhutchins** [comment] 2017-11-25 01:09
I am @linusg. I'll have some stuff tomorrow afternoon

**Comment by zainimran** [comment] 2017-11-25 14:10
Hey guys. I have been following this conversation and I feel like contributing too. I have experience in front end development and knowledge of the mean stack. Plus i can make really good hifi prototypes too. @sdhutchins<https://github.com/sdhutchins> and others please let me know how i can assist.


Zain.

On Nov 25, 2017, at 6:09 AM, Shaurita D. Hutchins <notifications@github.com<mailto:notifications@github.com>> wrote:


I am @linusg<https://github.com/linusg>. I'll have some stuff tomorrow afternoon

**Comment by linusg** [comment] 2017-11-25 14:49
@zainimran surely, let's wait for the mockups. Later on we will have enought to do for sure.

@sdhutchins so exited!

**Comment by sdhutchins** [comment] 2017-11-25 23:41
@linusg won't get to it tonight. *le sigh* I have some emergency lab work to do.

**Comment by linusg** [comment] 2017-11-26 00:38
No problem, take your time. For me it's not that important for *now* as it's pretty late here. These timezones suck though. Until then :sleeping:

**Comment by djalmaaraujo** [comment] 2017-11-26 17:12
I feel like everybody wants to do something. Let's do this..

I will deliver some mockups today and we create a schedule for the rest. Btw, feel free to post what ever you want here, @zainimran, you can start and we can review. It won't be a waste of time.

**Comment by linusg** [comment] 2017-11-27 19:41
> I'll have some stuff tomorrow afternoon

> I will deliver some mockups today

Any update here? :wink:

**Comment by zainimran** [comment] 2017-11-27 21:55
I tried something on proto.io since I am using that tool on another project right now. 
Link to the prototype: https://pr.to/O2X7Z9/
![capture](https://user-images.githubusercontent.com/17803773/33291513-dfb5f21e-d3e7-11e7-9b09-234a7096a5bc.PNG)

**Comment by linusg** [comment] 2017-11-27 22:21
@zainimran
Boom, here we go! Thanks for your work! What about moving the download button to below the list? And I find the down facing arrow rather confusing, seems like a second download button... However, I like the expected usage workflow, pasting a playlist link, (de) selecting some songs and hitting download :+1:

So, who agrees with this design along with my proposed change and who's willed working on what? :blush:

**Comment by linusg** [comment] 2017-11-27 22:22
Uh, and I think we might not use their icon for the application :neutral_face:

**Comment by zainimran** [comment] 2017-11-27 22:31
Yeah, the Spotify icon is there just as a placeholder until we design our own icon (assuming if we do).

The download button right next to the input box was intended as a button to fetch the playlist once there was a link in the input box.

Let’s see what others think too. I’ll be happy to make any changes which could improve our workflow 😊


Zain.

On Nov 28, 2017, at 3:22 AM, Linus Groh <notifications@github.com<mailto:notifications@github.com>> wrote:


Uh, and I think we might not use their icon for the application 😐

**Comment by djalmaaraujo** [comment] 2017-11-27 22:44
@zainimran Thanks for your contribution. Here's my 2 cents for the simplest MVP ever:

![start](https://user-images.githubusercontent.com/3402/33293367-72969896-d3c4-11e7-9007-6fe40993e888.png)
![loading](https://user-images.githubusercontent.com/3402/33293280-316c88c6-d3c4-11e7-91a3-73b83187586b.png)

![found](https://user-images.githubusercontent.com/3402/33293279-313e4de4-d3c4-11e7-87a1-a30936d3d3ce.png)
![not-found](https://user-images.githubusercontent.com/3402/33293281-319e3402-d3c4-11e7-8783-152f7c384590.png)

**Comment by djalmaaraujo** [comment] 2017-11-27 23:04
Leave comments, suggestions. This is the simplest MVP possible and simple. Because we can test the communication with the CLI and see how it's going to work.

**Comment by djalmaaraujo** [comment] 2017-11-27 23:05
To be honest, as a final user of this application, I can't see myself doing anything different than pasting a playlist link, pressing download and choosing a folder. Sure we can do more after the mvp, but for me, that would be more than enough.

**Comment by linusg** [comment] 2017-11-27 23:09
> Because we can test the communication with the CLI and see how it's going to work.

That's true. BUT I would love the feature of de-selecting songs, it's what annoys me with spotify-downloader the most. About the CLI, if we need more options ore output I'm sure I can do something about it :wink:

Most important for me right now: who will make the first step, starting with code? I think you had react in mind, but I would rather start with some simple markup, basic styles and JS.

Thoughts?
And, I highly vote for switching to `npm` which I love :P

**Comment by djalmaaraujo** [comment] 2017-11-27 23:17
> BUT I would love the feature of de-selecting songs, it's 

Sure, we can try to put this feature. But this would require more stuff, because the CLI don't return the artist name, album, etc, we only get the *.txt. It's a LOT of work to put in place api keys for spotify, a spotify application in developers console, etc.

> who will make the first step, starting with code?

This repo is open, feel free to jump. The code in place right now is already READY to go... react is installed, you can add css, html, etc.

> And, I highly vote for switching to npm which I love :P

What? I don't understand what you are saying. Are you talking about yarn? I don't think it's a safe approach to remove yarn, just because yarn exists because `npm` failed a lot with the community in the past year. Every project these days uses yarn as an alternative (that uses npm under the hood), so I strongly recommend to keep yarn. If you have any questions about how to use, feel free to ping me.

**Comment by djalmaaraujo** [comment] 2017-11-27 23:18
@linusg If you feel more confortable with with just plain html/css/js, feel free to put some codepen, jsfiddle, etc and I will port to the existing code for you, so you don't have to deal with react right now.

**Comment by linusg** [comment] 2017-11-27 23:23
> Sure, we can try to put this feature. But this would require more stuff, because the CLI don't return the artist name, album, etc, we only get the *.txt. It's a LOT of work to put in place api keys for spotify, a spotify application in developers console, etc.

As I said, I can easily add a flag to give us desired output we can parse.

> This repo is open, feel free to jump. The code in place right now is already READY to go... react is installed, you can add css, html, etc.

Sure. I will try starting tomorrow morning, when I have some hours open. (Now it's 0:20 here, so...)

> What? I don't understand what you are saying. Are you talking about yarn? I don't think it's a safe approach to remove yarn, just because yarn exists because npm failed a lot with the community in the past year. Every project these days uses yarn as an alternative (that uses npm under the hood), so I strongly recommend to keep yarn. If you have any questions about how to use, feel free to ping me.

So, this is a misunderstanding of mine, sorry. Didn't knew yarn uses npm under the hood, I will have to read up on that a little. Have you an example or two of how npm failed?
So, keeping yarn :smile: 

> @linusg If you feel more confortable with with just plain html/css/js, feel free to put some codepen, jsfiddle, etc and I will port to the existing code for you, so you don't have to deal with react right now.

I am comfortable with react but not as efficient as with oldschool HTML. :wink:
No problem with directly moving on to react, but expect some structuring issues soon or later...

**Comment by sdhutchins** [comment] 2017-11-27 23:30
I think we could break the app into phases with goals for each phase.

### Phase 1
- Download to a user selected folder by pasting a link of an album, song, or playlist.

### Phase 2
- Selecting which songs from a playlist or album to download.

### Phase 3
- Searching for a song, album, playlist and downloading it.

**Comment by sdhutchins** [comment] 2017-11-27 23:32
Breaking things into phases could help us better focus our efforts on the different features we'd like to see with the app. We could make all of those phases 1 phase and work towards implementation. Obviously, someone needs to be focusing on integrating the cli with the desktop app (I'm open to that).

**Comment by linusg** [comment] 2017-11-27 23:42
Talking about the CLI integration is important from the beginning on I think. For a quick start we should assume all required scripts and binaries are in `$PATH`. Next, we could work with this code:

```javascript
const ChildProcess = require('child_process');

ChildProcess.exec('python3 -V', (err, stdout, stderr) => {
  if (err)
    console.error(err);
  console.log(stdout);
  // console.log(stderr);
});
```

Which works like a charm in my `electron`-`react` setup:

![grafik](https://user-images.githubusercontent.com/19366641/33295308-fa204fa4-d3d4-11e7-8bd9-afc235a052a9.png)

**Comment by sdhutchins** [comment] 2017-11-27 23:47
This is my vision for the app - at least the first/initial release.

![spotifube](https://user-images.githubusercontent.com/20976111/33295440-fe7280a2-d39a-11e7-9c14-56160781dbf7.png)

**Comment by linusg** [comment] 2017-11-28 10:11
I will close this one for now, as we have reached this issue's aim: having some mockups :tada: 
Please have a further discussion in #4.

I will add the mockups to the issue mentioned in a few seconds.

**Closed as completed by linusg** 2017-11-28 10:11 UTC
Labels: help wanted, good first issue
